# Class description ----

#' `tdcmm` class
#'
#' @description The tdcmm class is a specialized type of data frame that is a
#' subclass of [tbl_df][tibble::tbl_df], also known as a "tibble". It is
#' designed to be used with `tidycomm` functions to provide additional
#' information and context to the output tibbles generated by these functions.
#' This subclass specifically augments output based on statistical tests, by
#' including the relevant model object(s) estimated during the analysis, as
#' well as any performed assumption checks.
#'
#' `tdcmm` objects in `tidycomm` are further subclassed with individual classes
#' handling visualization and printing per "output" type.
#'
#' @name tdcmm-class
#' @aliases tdcmm tdcmm-class
NULL

# Constructors ----

#' `tdcmm` output constructor
#'
#' @description
#' Creates a new `tdcmm` class output object.
#'
#' The `tdcmm` class is a subclass of a [`tbl_df`][tibble::tbl_df],
#' also know as a "tibble", used for augmenting output tibbles of `tidycomm`
#' functions with additional information. For output based on statistical tests,
#' the model object(s) estimated and any performed assumption checks.
#'
#' `tdcmm` objects in `tidycomm` are further subclassed with individual classes
#' handling visualization and printing per "output" type.
#'
#' @param x A [tibble][tibble::tibble-package].
#' @param func Function name called that produced this model.
#' @param data The [tibble] that served as input to the function.
#' @param model A list of model object(s) used in preparation of the output.
#'   Defaults to `NULL`. A single model should be wrapped in a list of length
#'   `1`.
#' @param checks A list of assumption check object(s) used in preparation of the
#'   output. Defaults to `NULL`.
#' @param params A named list of parameters originally passed to the call.
#'   Defaults to an empty list.
new_tdcmm <- function(x, func, data, model = NULL, checks = NULL, params = list()) {
  stopifnot(tibble::is_tibble(x))
  stopifnot(func != "")
  stopifnot(tibble::is_tibble(data))
  stopifnot(is.list(model) | is.null(model))
  stopifnot(is.list(checks) | is.null(checks))
  stopifnot(is.list(params))

  structure(
    x,
    class = c("tdcmm", class(x)),
    func = func,
    data = data,
    params = params,
    model = model,
    checks = checks
  )
}

# Test ----

#' @describeIn new_tdcmm Test for class `tdcmm`
is_tdcmm <- function(x) {
  inherits(x, "tdcmm")
}


# Accessors ----

#' Access model(s) used to estimate output
#'
#' Returns model objects used to estimate `tdcmm` output.
#'
#' @param x `tdcmm` output
#' @param ... other arguments
#'
#' @returns A model object or a list of model objects
#'
#' @export
model <- function(x, ...) {
  UseMethod("model")
}

#' @export
model.tdcmm <- function(x, ...) {
  model <- attr(x, "model")
  if (is.null(model)) {
    x_string <- deparse(substitute(x))
    x_string <- ifelse(x_string == ".",
                       "The provided object",
                       glue("'{x_string}'"))
    warning(glue("{x_string} does not contain any model."),
            call. = FALSE)
  }
  if (length(model) == 1) model[[1]] else model
}
#' Access visualization used to estimate output
#'
#' Returns [ggplot2] visualization appropriate to respective `tdcmm` model
#' (see list below). Returns `NULL` (and a warning) if not visualization has
#' been implemented for the particular model.
#'
#' - `describe`: horizontal box plot depicting a box from Q25 to Q75, a thick
#' line for Mdn, and two whiskers to Min/Max respectively;
#' no additional arguments
#' - `describe_cat`: horizontal bar plot depicting number of occurrences;
#' no additional arguments
#' - `tab_frequencies`: either a histogram (if 1 variable is given) or multiple
#' histograms wrapped, 4+ variables also issue a warning about readability;
#' no additional arguments
#' - `crosstab`: horizontal stacked bar plot, either absolute or relative
#' (depending on `percentages`)
#'
#' @param x `tdcmm` output
#' @param ... other arguments
#'
#' @returns A [ggplot2] object
#'
#' @export
visualize <- function(x, ...) {
  UseMethod("visualize")
}

#' @export
visualize.tdcmm <- function(x, ...) {
  return(warn_about_missing_visualization(x))
}
